# Generated by Django 4.1.4 on 2022-12-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumb', models.CharField(blank=True, max_length=50, null=True)),
                ('key', models.CharField(max_length=100)),
                ('times', models.CharField(max_length=50)),
                ('step', models.TextField()),
                ('ingredient', models.TextField()),
            ],
        ),
    ]
